/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2018-12-05 17:08:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Arrays;
import java.util.ArrayList;

public final class MostrarResultado_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Japancar MM, distribuidor oficial de Mazda y Mitsubishi en Barcelona\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"Japancar MM, Mazda, Mitsubishi, Barcelona\">\r\n");
      out.write("\t<title>Japancar MM | Mostrar</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.3.1/css/all.css\" integrity=\"sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\tbody{\r\n");
      out.write("      \t\tbackground-color: #E9967A; \r\n");
      out.write("      \t}\r\n");
      out.write("      \t\r\n");
      out.write("\t\tmain{\r\n");
      out.write("\t\t\tfont-size: 1em;\r\n");
      out.write("\t\t\ttext-align: left;\r\n");
      out.write("\t\t\tpadding-top: 200px;\r\n");
      out.write("      \t\tpadding-right: 20px;\r\n");
      out.write("      \t\tpadding-bottom: 275px;\r\n");
      out.write("      \t\tpadding-left: 20px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\th4{\r\n");
      out.write("\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttable, th, td {\r\n");
      out.write("  \t\t\tborder: 1px solid black;\r\n");
      out.write("  \t\t\ttext-align: center;\r\n");
      out.write("  \t\t\tvertical-align: middle;\r\n");
      out.write("  \t\t\tpadding-top: 5px;\r\n");
      out.write("      \t\tpadding-right: 5px;\r\n");
      out.write("      \t\tpadding-bottom: 5px;\r\n");
      out.write("      \t\tpadding-left: 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t<h1><span>Japancar</span> MM</h1>\r\n");
      out.write("\t\t\t\t<p>Concesionario Oficial Mazda y Mitsubishi</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.html\">Inicio<hr></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"SobreNosostros.html\">Sobre Nosotros<hr></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Concesionarios.html\">Concesionarios<hr></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Contacto.html\">Contacto<hr></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<main>\r\n");
      out.write("\t");

	//ArrayList<String> datos = new ArrayList<String>(); //recogerlo del servlet "anterior" con request.getAttribute("datos")
	//request.getAttribute("datos") devuelve Object, cast (ArrayList<String>)
	ArrayList<Object[]> datos = (ArrayList<Object[]>) session.getAttribute("datosFiltrados"); //para mostrar el número de coches seleccionados
	
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!--COCHES SELECCIONADOS: <!%= Arrays.toString((String[])session.getAttribute(\"checkbox\")) %> -->\r\n");
      out.write("\t<h4>Número de coches seleccionados: ");
      out.print(datos.size());
      out.write("</h4>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr bgcolor= \"#556B2F\">\r\n");
      out.write("\t<td><strong>Número</strong></td>\r\n");
      out.write("\t<td><strong>Isbn</strong></td>\r\n");
      out.write(" \t<td><strong>Marca</strong></td>\r\n");
      out.write("    <td><strong>Modelo</strong></td>\r\n");
      out.write("    <td><strong>Acabado</strong></td>\r\n");
      out.write("    <td><strong>Número de puertas</strong></td>\r\n");
      out.write("    <td><strong>Tipo de carrocería</strong></td>\r\n");
      out.write("    <td><strong>Cambio</strong></td>\r\n");
      out.write("    <td><strong>Combustible</strong></td>\r\n");
      out.write(" \t<td><strong>Potencia (CV)</strong></td>\r\n");
      out.write("    <td><strong>Consumo medio (l)</strong></td>\r\n");
      out.write("    <td><strong>Longitud (mm)</strong></td>\r\n");
      out.write("    <td><strong>Anchura (mm)</strong></td>\r\n");
      out.write("    <td><strong>Altura (mm)</strong></td>\r\n");
      out.write("    <td><strong>Maletero (l)</strong></td>\r\n");
      out.write("    <td><strong>Años de garantía</strong></td>\r\n");
      out.write(" \t<td><strong>Precio (euros)</strong></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\t");

	//datos.add("num");
		
	for (int i=0; i<datos.size(); i++){
		Object[] coche = datos.get(i);
		if (i%2==0){
      out.write("\r\n");
      out.write("\t\t\t<tr bgcolor= \"#8470FF\" >\r\n");
      out.write("\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t<tr bgcolor= \"#8433FF\" >\r\n");
      out.write("\t\t");
}
      out.write("\t\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( i );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[0] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[1] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[2] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[3] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[4] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[5] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[6] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[7] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[8] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[9] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[10] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[11] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[12] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[13] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[14] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print( coche[15] );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<a style='color:blue' href='./index.html'>Volver a la página de inicio</a>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<a style='color:blue' href='./servletcerrarsession'>Desconectar</a>\r\n");
      out.write("\t\t</main>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<section>\r\n");
      out.write("\t\t\t\t<div class=\"menu_footer1\">\r\n");
      out.write("\t\t\t\t\t<a href=\"Privacidad.html\">Política de Privacidad</a> &nbsp|&nbsp <a href=\"Cookies.html\">Cookies</a> &nbsp|&nbsp <a href=\"MapaDelSitio.html\">Mapa del sitio</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"menu_footer2\">\r\n");
      out.write("\t\t\t\t\t<a href=\"https://www.mazda.es/\">Web Oficial Mazda</a> &nbsp|&nbsp <a href=\"https://www.mitsubishi-motors.es\">Web Oficial Mitsubishi Motors</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<div class=\"linea\">\r\n");
      out.write("\t\t\t\t<p class=\"copyright\">&copy; 2018 Japancar MM, S.L. Todos los derechos reservados</p>\r\n");
      out.write("\t\t\t\t<div class=\"redes\">\r\n");
      out.write("\t\t\t\t\t<p>Síguenos en</p>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://es-es.facebook.com/\"><img src=\"img/Facebook.jpg\" alt=\"Facebook\"></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.instagram.com/?hl=es\"><img src=\"img/Instagram.jpg\" alt=\"Instagram\"></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://twitter.com/?lang=es\"><img src=\"img/Twitter.jpg\" alt=\"Twitter\"></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.youtube.com/?gl=ES&hl=es\"><img src=\"img/Youtube.jpg\" alt=\"Youtube\"></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
